src/huginn/config/routes.rb
Huginn::Application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      delete :remove_events
    end

    collection do
      post :propagate
      get :type_details
      get :event_descriptions
      get :diagram
    end

    resources :logs, :only => [:index] do
      collection do
        delete :clear
      end
    end
  end

  resources :events, :only => [:index, :show, :destroy] do
    member do
      post :reemit
    end
  end

  resources :user_credentials, :except => :show

  match "/worker_status" => "worker_status#show"

  post "/users/:user_id/update_location/:secret" => "user_location_updates#create"
  post "/users/:user_id/webhooks/:agent_id/:secret" => "webhooks#create"

#  match "/delayed_job" => DelayedJobWeb, :anchor => false
  devise_for :users, :sign_out_via => [ :post, :delete ]

  match "/about" => "home#about"
  root :to => "home#index"
end

src/huginn/app/views/layouts/_messages.html.erb
<% if flash.keys.length > 0 %>
  <div class="flash">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
<% end %>

src/huginn/app/views/layouts/_navigation.html.erb
<%= link_to "Huginn", root_path, :class => 'brand' %>

<% if user_signed_in? %>
  <ul class='nav pull-left'>
    <%= nav_link "Agents", agents_path %>
    <%= nav_link "Events", events_path %>
    <%= nav_link "Credentials", user_credentials_path %>
  </ul>
<% end %>

<ul class="nav pull-right">
  <% if user_signed_in? %>

    <form class="navbar-search pull-left">
      <input type="text" class="search-query" id='agent-navigate' autocomplete="off" placeholder="Search">
      <%= image_tag "spinner-arrows.gif", :class => "spinner" %>
    </form>

    <li id='job-indicator'>
      <a href="/delayed_job">
        <span class="badge"><i class="icon-refresh icon-white"></i> <span class='number'>0</span></span>
      </a>
    </li>

    <li id='event-indicator'>
      <a href="#">
        <span class="badge"><i class="icon-random icon-white"></i> <span class='number'>0</span> new events</span>
      </a>
    </li>
  <% end %>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Account
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
      <li>
        <% if user_signed_in? %>
          <%= link_to 'Account', edit_user_registration_path, :tabindex => "-1" %>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, :tabindex => "-1" %>
        <% end %>
      </li>

      <li>
        <%= link_to 'About', 'https://github.com/cantino/huginn', :tabindex => "-1" %>
      </li>

      <li>
        <% if user_signed_in? %>
          <%= link_to 'Logout', destroy_user_session_path, :method => :delete, :tabindex => "-1" %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, :tabindex => "-1" %>
        <% end %>
      </li>
    </ul>
  </li>
</ul>

src/huginn/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Huginn" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>

    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>
      var agentPaths = {};
      <% if current_user -%>
        var myAgents = <%= Utils.jsonify(current_user.agents.select([:name, :id, :schedule]).inject({}) {|m, a| m[a.name] = agent_path(a); m }) %>;
        $.extend(agentPaths, myAgents);
      <% end -%>
      agentPaths["All Agents Index"] = <%= Utils.jsonify agents_path %>;
      agentPaths["New Agent"] = <%= Utils.jsonify new_agent_path %>;
      agentPaths["Account"] = <%= Utils.jsonify edit_user_registration_path %>;
      agentPaths["Events Index"] = <%= Utils.jsonify events_path %>;
      agentPaths["View Agent Diagram"] = <%= Utils.jsonify diagram_agents_path %>;
      agentPaths["Run Event Propagation"] = { url: <%= Utils.jsonify propagate_agents_path %>, method: 'POST' };
      var agentNames = [];
      $.each(agentPaths, function(name, v) { agentNames.push(name); });
    </script>
  </body>
</html>