src/huginn/config/routes.rb
Huginn::Application.routes.draw do
  resources :agents do
    member do
      post :run
      post :handle_details_post
      delete :remove_events
    end

    collection do
      post :propagate
      get :type_details
      get :event_descriptions
      get :diagram
    end

    resources :logs, :only => [:index] do
      collection do
        delete :clear
      end
    end
  end

  resources :events, :only => [:index, :show, :destroy] do
    member do
      post :reemit
    end
  end

  resources :user_credentials, :except => :show

  match "/worker_status" => "worker_status#show"

  post "/users/:user_id/update_location/:secret" => "user_location_updates#create"
  post "/users/:user_id/webhooks/:agent_id/:secret" => "webhooks#create"

#  match "/delayed_job" => DelayedJobWeb, :anchor => false
  devise_for :users, :sign_out_via => [ :post, :delete ]

  match "/about" => "home#about"
  root :to => "home#index"
end

src/huginn/app/models/agent.rb
require 'json_serialized_field'
require 'assignable_types'
require 'markdown_class_attributes'
require 'utils'

# Agent is the core class in Huginn, representing a configurable, schedulable, reactive system with memory that can
# be sub-classed for many different purposes.  Agents can emit Events, as well as receive them and react in many different ways.
# The basic Agent API is detailed on the Huginn wiki: https://github.com/cantino/huginn/wiki/Creating-a-new-agent
class Agent < ActiveRecord::Base
  include AssignableTypes
  include MarkdownClassAttributes
  include JSONSerializedField

  markdown_class_attributes :description, :event_description

  load_types_in "Agents"

  SCHEDULES = %w[every_2m every_5m every_10m every_30m every_1h every_2h every_5h every_12h every_1d every_2d every_7d
                 midnight 1am 2am 3am 4am 5am 6am 7am 8am 9am 10am 11am noon 1pm 2pm 3pm 4pm 5pm 6pm 7pm 8pm 9pm 10pm 11pm never]

  EVENT_RETENTION_SCHEDULES = [["Forever", 0], ["1 day", 1], *([2, 3, 4, 5, 7, 14, 21, 30, 45, 90, 180, 365].map {|n| ["#{n} days", n] })]

  attr_accessible :options, :memory, :name, :type, :schedule, :source_ids, :keep_events_for

  json_serialize :options, :memory

  validates_presence_of :name, :user
  validates_inclusion_of :keep_events_for, :in => EVENT_RETENTION_SCHEDULES.map(&:last)
  validate :sources_are_owned
  validate :validate_schedule
  validate :validate_options

  after_initialize :set_default_schedule
  before_validation :set_default_schedule
  before_validation :unschedule_if_cannot_schedule
  before_save :unschedule_if_cannot_schedule
  before_create :set_last_checked_event_id
  after_save :possibly_update_event_expirations

  belongs_to :user, :inverse_of => :agents
  has_many :events, :dependent => :delete_all, :inverse_of => :agent, :order => "events.id desc"
  has_one  :most_recent_event, :inverse_of => :agent, :class_name => "Event", :order => "events.id desc"
  has_many :logs, :dependent => :delete_all, :inverse_of => :agent, :class_name => "AgentLog", :order => "agent_logs.id desc"
  has_many :received_events, :through => :sources, :class_name => "Event", :source => :events, :order => "events.id desc"
  has_many :links_as_source, :dependent => :delete_all, :foreign_key => "source_id", :class_name => "Link", :inverse_of => :source
  has_many :links_as_receiver, :dependent => :delete_all, :foreign_key => "receiver_id", :class_name => "Link", :inverse_of => :receiver
  has_many :sources, :through => :links_as_receiver, :class_name => "Agent", :inverse_of => :receivers
  has_many :receivers, :through => :links_as_source, :class_name => "Agent", :inverse_of => :sources

  scope :of_type, lambda { |type|
    type = case type
             when String, Symbol, Class
               type.to_s
             when Agent
               type.class.to_s
             else
               type.to_s
           end
    where(:type => type)
  }

  def check
    # Implement me in your subclass of Agent.
  end

  def default_options
    # Implement me in your subclass of Agent.
    {}
  end

  def receive(events)
    # Implement me in your subclass of Agent.
  end

  def receive_webhook(params)
    # Implement me in your subclass of Agent.
    ["not implemented", 404]
  end

  # Implement me in your subclass to decide if your Agent is working.
  def working?
    raise "Implement me in your subclass"
  end

  def validate_options
    # Implement me in your subclass to test for valid options.
  end

  def event_created_within?(days)
    last_event_at && last_event_at > days.to_i.days.ago
  end

  def recent_error_logs?
    last_event_at && last_error_log_at && last_error_log_at > (last_event_at - 2.minutes)
  end

  def create_event(attrs)
    if can_create_events?
      events.create!({ :user => user, :expires_at => new_event_expiration_date }.merge(attrs))
    else
      error "This Agent cannot create events!"
    end
  end

  def credential(name)
    @credential_cache ||= {}
    if @credential_cache.has_key?(name)
      @credential_cache[name]
    else
      @credential_cache[name] = user.user_credentials.where(:credential_name => name).first.try(:credential_value)
    end
  end

  def reload
    @credential_cache = {}
    super
  end

  def new_event_expiration_date
    keep_events_for > 0 ? keep_events_for.days.from_now : nil
  end

  def update_event_expirations!
    if keep_events_for == 0
      events.update_all :expires_at => nil
    else
      events.update_all "expires_at = DATE_ADD(`created_at`, INTERVAL #{keep_events_for.to_i} DAY)"
    end
  end

  def make_message(payload, message = options[:message])
    message.gsub(/<([^>]+)>/) { Utils.value_at(payload, $1) || "??" }
  end

  def trigger_webhook(params)
    receive_webhook(params).tap do
      self.last_webhook_at = Time.now
      save!
    end
  end

  def default_schedule
    self.class.default_schedule
  end

  def cannot_be_scheduled?
    self.class.cannot_be_scheduled?
  end

  def can_be_scheduled?
    !cannot_be_scheduled?
  end

  def cannot_receive_events?
    self.class.cannot_receive_events?
  end

  def can_receive_events?
    !cannot_receive_events?
  end

  def cannot_create_events?
    self.class.cannot_create_events?
  end

  def can_create_events?
    !cannot_create_events?
  end

  def log(message, options = {})
    puts "Agent##{id}: #{message}" unless Rails.env.test?
    AgentLog.log_for_agent(self, message, options)
  end

  def error(message, options = {})
    log(message, options.merge(:level => 4))
  end

  def delete_logs!
    logs.delete_all
    update_column :last_error_log_at, nil
  end

  # Validations and Callbacks

  def sources_are_owned
    errors.add(:sources, "must be owned by you") unless sources.all? {|s| s.user == user }
  end

  def validate_schedule
    unless cannot_be_scheduled?
      errors.add(:schedule, "is not a valid schedule") unless SCHEDULES.include?(schedule.to_s)
    end
  end

  def set_default_schedule
    self.schedule = default_schedule unless schedule.present? || cannot_be_scheduled?
  end

  def unschedule_if_cannot_schedule
    self.schedule = nil if cannot_be_scheduled?
  end

  def set_last_checked_event_id
    if newest_event_id = Event.order("id desc").limit(1).pluck(:id).first
      self.last_checked_event_id = newest_event_id
    end
  end

  def possibly_update_event_expirations
    update_event_expirations! if keep_events_for_changed?
  end

  # Class Methods

  class << self
    def cannot_be_scheduled!
      @cannot_be_scheduled = true
    end

    def cannot_be_scheduled?
      !!@cannot_be_scheduled
    end

    def default_schedule(schedule = nil)
      @default_schedule = schedule unless schedule.nil?
      @default_schedule
    end

    def cannot_create_events!
      @cannot_create_events = true
    end

    def cannot_create_events?
      !!@cannot_create_events
    end

    def cannot_receive_events!
      @cannot_receive_events = true
    end

    def cannot_receive_events?
      !!@cannot_receive_events
    end

    # Find all Agents that have received Events since the last execution of this method.  Update those Agents with
    # their new `last_checked_event_id` and queue each of the Agents to be called with #receive using `async_receive`.
    # This is called by bin/schedule.rb periodically.
    def receive!
      Agent.transaction do
        sql = Agent.
                select("agents.id AS receiver_agent_id, sources.id AS source_agent_id, events.id AS event_id").
                joins("JOIN links ON (links.receiver_id = agents.id)").
                joins("JOIN agents AS sources ON (links.source_id = sources.id)").
                joins("JOIN events ON (events.agent_id = sources.id AND events.id > links.event_id_at_creation)").
                where("agents.last_checked_event_id IS NULL OR events.id > agents.last_checked_event_id").to_sql

        agents_to_events = {}
        Agent.connection.select_rows(sql).each do |receiver_agent_id, source_agent_id, event_id|
          agents_to_events[receiver_agent_id] ||= []
          agents_to_events[receiver_agent_id] << event_id
        end

        event_ids = agents_to_events.values.flatten.uniq.compact

        Agent.where(:id => agents_to_events.keys).each do |agent|
          agent.update_attribute :last_checked_event_id, event_ids.max
          Agent.async_receive(agent.id, agents_to_events[agent.id].uniq)
        end

        {
          :agent_count => agents_to_events.keys.length,
          :event_count => event_ids.length
        }
      end
    end

    # Given an Agent id and an array of Event ids, load the Agent, call #receive on it with the Event objects, and then
    # save it with an updated `last_receive_at` timestamp.
    #
    # This method is tagged with `handle_asynchronously` and will be delayed and run with delayed_job.  It accepts Agent
    # and Event ids instead of a literal ActiveRecord models because it is preferable to serialize delayed_jobs with ids.
    def async_receive(agent_id, event_ids)
      agent = Agent.find(agent_id)
      begin
        agent.receive(Event.where(:id => event_ids))
        agent.last_receive_at = Time.now
        agent.save!
      rescue => e
        agent.error "Exception during receive: #{e.message} -- #{e.backtrace}"
        raise
      end
    end
    handle_asynchronously :async_receive

    # Given a schedule name, run `check` via `bulk_check` on all Agents with that schedule.
    # This is called by bin/schedule.rb for each schedule in `SCHEDULES`.
    def run_schedule(schedule)
      return if schedule == 'never'
      types = where(:schedule => schedule).group(:type).pluck(:type)
      types.each do |type|
        type.constantize.bulk_check(schedule)
      end
    end

    # Schedule `async_check`s for every Agent on the given schedule.  This is normally called by `run_schedule` once
    # per type of agent, so you can override this to define custom bulk check behavior for your custom Agent type.
    def bulk_check(schedule)

src/huginn/app/models/agents/adioso_agent.rb
module Agents
  class AdiosoAgent < Agent

    cannot_receive_events!

  	default_schedule "every_1d"

    description <<-MD
  		The Adioso Agent will tell you the minimum airline prices between a pair of cities, and within a certain period of time.
      The currency is USD. Please make sure that the difference between `start_date` and `end_date` is less than 150 days. You will need to contact [Adioso](http://adioso.com/)
  		for a `username` and `password`.
    MD

    event_description <<-MD
      If flights are present then events look like:

          {
            "cost": 75.23,
            "date": "June 25, 2013",
  			    "route": "New York to Chicago"
          }

      otherwise
    
          {
            "nonetodest": "No flights found to the specified destination"
          }
    MD

    def default_options
      {
        'start_date' => Date.today.httpdate[0..15],
        'end_date'   => Date.today.plus_with_duration(100).httpdate[0..15],
        'from'       => "New York",
        'to'         => "Chicago",
        'username'   => "xx",
        'password'   => "xx",
				'expected_update_period_in_days' => "1"
      }
    end

    def working?
      event_created_within?(options['expected_update_period_in_days']) && !recent_error_logs?
    end

    def validate_options
			unless %w[start_date end_date from to username password expected_update_period_in_days].all? { |field| options[field].present? }
				errors.add(:base, "All fields are required")
			end
		end

    def date_to_unix_epoch(date)
      date.to_time.to_i
    end

    def check
      auth_options = {:basic_auth => {:username =>options[:username], :password=>options['password']}}
      parse_response = HTTParty.get "http://api.adioso.com/v2/search/parse?q=#{URI.encode(options['from'])}+to+#{URI.encode(options['to'])}", auth_options
      fare_request = parse_response["search_url"].gsub /(end=)(\d*)([^\d]*)(\d*)/, "\\1#{date_to_unix_epoch(options['end_date'])}\\3#{date_to_unix_epoch(options['start_date'])}"
      fare = HTTParty.get fare_request, auth_options

			if fare["warnings"]
				create_event :payload => fare["warnings"]
			else
				event = fare["results"].min {|a,b| a["cost"] <=> b["cost"]}
				event["date"]  = Time.at(event["date"]).to_date.httpdate[0..15]
				event["route"] = "#{options['from']} to #{options['to']}"
				create_event :payload => event
			end
    end
  end
end

src/huginn/app/models/agents/digest_email_agent.rb
module Agents
  class DigestEmailAgent < Agent
    include EmailConcern

    default_schedule "5am"

    cannot_create_events!

    description <<-MD
      The DigestEmailAgent collects any Events sent to it and sends them all via email when run.
      The email will be sent to your account's address and will have a `subject` and an optional `headline` before
      listing the Events.  If the Events' payloads contain a `message`, that will be highlighted, otherwise everything in
      their payloads will be shown.

      Set `expected_receive_period_in_days` to the maximum amount of time that you'd expect to pass between Events being received by this Agent.
    MD

    def default_options
      {
          'subject' => "You have some notifications!",
          'headline' => "Your notifications:",
          'expected_receive_period_in_days' => "2"
      }
    end

    def receive(incoming_events)
      incoming_events.each do |event|
        self.memory['queue'] ||= []
        self.memory['queue'] << event.payload
        self.memory['events'] ||= []
        self.memory['events'] << event.id
      end
    end

    def check
      if self.memory['queue'] && self.memory['queue'].length > 0
        ids = self.memory['events'].join(",")
        groups = self.memory['queue'].map { |payload| present(payload) }
        log "Sending digest mail to #{user.email} with events [#{ids}]"
        SystemMailer.delay.send_message(:to => user.email, :subject => options['subject'], :headline => options['headline'], :groups => groups)
        self.memory['queue'] = []
        self.memory['events'] = []
      end
    end
  end
end

src/huginn/app/models/agents/email_agent.rb
module Agents
  class EmailAgent < Agent
    include EmailConcern

    cannot_be_scheduled!
    cannot_create_events!

    description <<-MD
      The EmailAgent sends any events it receives via email immediately.
      The email will be sent to your account's address and will have a `subject` and an optional `headline` before
      listing the Events.  If the Events' payloads contain a `:message`, that will be highlighted, otherwise everything in
      their payloads will be shown.

      Set `expected_receive_period_in_days` to the maximum amount of time that you'd expect to pass between Events being received by this Agent.
    MD

    def default_options
      {
          'subject' => "You have a notification!",
          'headline' => "Your notification:",
          'expected_receive_period_in_days' => "2"
      }
    end

    def receive(incoming_events)
      incoming_events.each do |event|
        log "Sending digest mail to #{user.email} with event #{event.id}"
        SystemMailer.delay.send_message(:to => user.email, :subject => options['subject'], :headline => options['headline'], :groups => [present(event.payload)])
      end
    end
  end
end

src/huginn/app/models/agents/event_email_agent.rb
module Agents
  class EventEmailAgent < Agent
    include EmailConcern

    cannot_be_scheduled!
    cannot_create_events!

    description <<-MD
      The EventEmailAgent sends any events it receives via email.
      The email will be sent to your account's address and will have a `subject` and an optional `headline` before
      listing the Events.  If the Events' payloads contain a `:message`, that will be highlighted, otherwise everything in
      their payloads will be shown.

      Set `expected_receive_period_in_days` to the maximum amount of time that you'd expect to pass between Events being received by this Agent.
    MD

    def default_options
      {
          :subject => "You have a notification!",
          :headline => "Your notification:",
          :expected_receive_period_in_days => "2"
      }
    end

    def receive(incoming_events)
      incoming_events.each do |event|
        log "Sending digest mail to #{user.email} with event #{event.id}"
        SystemMailer.delay.send_message(:to => user.email, :subject => options[:subject], :headline => options[:headline], :groups => [present(event.payload)])
      end
    end
  end
end

src/huginn/app/views/agents/diagram.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h2>Agent Event Flow</h2>
      </div>
      <div class="btn-group">
        <%= link_to '<i class="icon-chevron-left"></i> Back'.html_safe, agents_path, class: "btn" %>
      </div>

      <div class='digraph'>
        <%
           dot_format_string = "digraph foo {"
           @agents.each.with_index do |agent, index|
             dot_format_string += "\"#{agent.name}\";"
             agent.receivers.each do |receiver|
               dot_format_string += "\"#{agent.name}\"->\"#{receiver.name}\";"
             end
           end
           dot_format_string = dot_format_string + "}"
        %>

        <img src="https://chart.googleapis.com/chart?cht=gv&chl=<%= CGI::escape dot_format_string %>" />
      </div>
    </div>
  </div>
</div>

src/huginn/app/views/agents/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h2>
          Editing your <%= @agent.short_type %>
          <%= image_tag "spinner-arrows.gif", :class => "spinner", :id => 'agent-spinner' %>
        </h2>
      </div>

      <%= render 'form' %>

      <div class="btn-group">
        <%= link_to '<i class="icon-chevron-left"></i> Back'.html_safe, agents_path, class: "btn" %>
        <%= link_to '<i class="icon-asterisk"></i> Show'.html_safe, agent_path(@agent), class: "btn" %>
      </div>
    </div>
  </div>
</div>

src/huginn/app/views/agents/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h2>Your Agents</h2>
      </div>

      <table class='table table-striped'>
        <tr>
          <th>Name</th>
          <th>Schedule</th>
          <th>Last Check</th>
          <th>Last Event Out</th>
          <th>Last Event In</th>
          <th>Events Created</th>
          <th>Working?</th>
          <th></th>
        </tr>

        <% @agents.each do |agent| %>
          <tr>
            <td>
              <%= agent.name %>
              <br/>
              <span class='muted'><%= agent.short_type.titleize %></span>
            </td>
            <td>
              <% if agent.can_be_scheduled? %>
                <%= agent.schedule.to_s.humanize.titleize %>
              <% else %>
                <span class='not-applicable'></span>
              <% end %>
            </td>
            <td>
              <% if agent.can_be_scheduled? %>
                <%= agent.last_check_at ? time_ago_in_words(agent.last_check_at) + " ago" : "never" %>
              <% else %>
                <span class='not-applicable'></span>
              <% end %>
            </td>
            <td>
              <% if agent.can_create_events? %>
                <%= agent.last_event_at ? time_ago_in_words(agent.last_event_at) + " ago" : "never" %>
              <% else %>
                <span class='not-applicable'></span>
              <% end %>
            </td>
            <td>
              <% if agent.can_receive_events? %>
                <%= agent.last_receive_at ? time_ago_in_words(agent.last_receive_at) + " ago" : "never" %>
              <% else %>
                <span class='not-applicable'></span>
              <% end %>
            </td>
            <td>
              <% if agent.can_create_events? %>
                <%= link_to(agent.events_count || 0, events_path(:agent => agent.to_param)) %>
              <% else %>
                <span class='not-applicable'></span>
              <% end %>
            </td>
            <td><%= working(agent) %></td>
            <td>
              <div class="btn-group">
                <%= link_to 'Show', agent_path(agent), class: "btn btn-mini" %>
                <%= link_to 'Edit', edit_agent_path(agent), class: "btn btn-mini" %>
                <%= link_to 'Delete', agent_path(agent), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini" %>
                <% if agent.can_be_scheduled? %>
                  <%= link_to 'Run', run_agent_path(agent, :return => "index"), method: :post, class: "btn btn-mini" %>
                <% else %>
                  <%= link_to 'Run', "#", class: "btn btn-mini disabled" %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </table>

      <%= paginate @agents, :theme => 'twitter-bootstrap' %>

      <br/>

      <div class="btn-group">
        <%= link_to '<i class="icon-plus"></i> New Agent'.html_safe, new_agent_path, class: "btn" %>
        <%= link_to '<i class="icon-refresh"></i> Run event propagation'.html_safe, propagate_agents_path, method: 'post', class: "btn" %>
        <%= link_to '<i class="icon-random"></i> View diagram'.html_safe, diagram_agents_path, class: "btn" %>
      </div>
    </div>
  </div>
</div>

src/huginn/app/views/agents/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='span12'>
      <div class="page-header">
        <h2>
          Create a new Agent
          <%= image_tag "spinner-arrows.gif", :class => "spinner", :id => 'agent-spinner' %>
        </h2>
      </div>

      <%= render 'form' %>

      <div class="btn-group">
        <%= link_to '<i class="icon-chevron-left"></i> Back'.html_safe, agents_path, class: "btn" %>
      </div>
    </div>
  </div>
</div>

src/huginn/app/views/agents/show.html.erb
<div class='container agent-show'>
  <div class='row'>
    <div class='span12'>

      <div class="tabbable tabs-left">
        <ul class="nav nav-tabs" id="show-tabs">
          <% if agent_show_view(@agent).present? %>
            <li class='active'><a href="#summary" data-toggle="tab"><i class='icon-picture'></i> Summary</a></li>
            <li><a href="#details" data-toggle="tab"><i class='icon-indent-left'></i> Details</a></li>
          <% else %>
            <li class='disabled'><a><i class='icon-picture'></i> Summary</a></li>
            <li class='active'><a href="#details" data-toggle="tab"><i class='icon-indent-left'></i> Details</a></li>
          <% end %>
          <li><a href="#logs" data-toggle="tab" data-agent-id="<%= @agent.id %>" class='<%= @agent.recent_error_logs? ? 'recent-errors' : '' %>'><i class='icon-list-alt'></i> Logs</a></li>

          <% if @agent.can_create_events? && @agent.events.count > 0 %>
            <li><%= link_to '<i class="icon-random"></i> Events'.html_safe, events_path(:agent => @agent.to_param) %></li>
          <% end %>
          <li><%= link_to '<i class="icon-chevron-left"></i> Back'.html_safe, agents_path %></li>
          <li><%= link_to '<i class="icon-pencil"></i> Edit'.html_safe, edit_agent_path(@agent) %></li>

          <% if @agent.can_be_scheduled? || @agent.events.count > 0 %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Actions <b class="caret"></b></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                <% if @agent.can_be_scheduled? %>
                  <li>
                    <%= link_to '<i class="icon-refresh"></i> Run'.html_safe, run_agent_path(@agent, :return => "show"), method: :post, :tabindex => "-1" %>
                  </li>
                <% end %>

                <% if @agent.can_create_events? && @agent.events.count > 0 %>
                  <li>
                    <%= link_to '<i class="icon-trash"></i> Delete all events'.html_safe, remove_events_agent_path(@agent), method: :delete, data: {confirm: 'Are you sure you want to delete ALL events for this Agent?'}, :tabindex => "-1" %>
                  </li>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>

        <div class="tab-content">
          <div class="tab-pane <%= agent_show_view(@agent).present? ? "active" : "disabled" %>" id="summary">
            <h2><%= @agent.name %> Summary</h2>

            <% if agent_show_view(@agent).present? %>
              <div class="show-view <%= agent_show_class(@agent) %>">
                <%= render agent_show_view(@agent) %>
              </div>
            <% end %>
          </div>

          <div class="tab-pane" id="logs" data-agent-id="<%= @agent.id %>">
            <h2>
              <%= @agent.name %> Logs
              <%= image_tag "spinner-arrows.gif", :class => "spinner" %>
              <i class="icon-refresh action-icon refresh"></i>
              <i class="icon-trash action-icon clear"></i>
            </h2>
            <div class='logs'>
              Just a moment...
            </div>
          </div>

          <div class="tab-pane <%= agent_show_view(@agent).present? ? "" : "active" %>" id="details">
            <h2><%= @agent.name %> Details</h2>

            <p>
              <b>Type:</b>
              <%= @agent.short_type.titleize %>
            </p>

            <% if @agent.can_be_scheduled? %>
              <p>
                <b>Schedule:</b>
                <%= (@agent.schedule || "n/a").humanize.titleize %>
              </p>

              <p>
                <b>Last checked:</b>
                <%= @agent.last_check_at ? time_ago_in_words(@agent.last_check_at) + " ago" : "never" %>
              </p>
            <% end %>

            <% if @agent.can_create_events? %>
              <p>
                <b>Keep events:</b>
                <%= (Agent::EVENT_RETENTION_SCHEDULES.detect {|s| s.last == @agent.keep_events_for } || [@agent.keep_events_for]).first %>
              </p>

              <p>
                <b>Last event created:</b>
                <%= @agent.last_event_at ? time_ago_in_words(@agent.last_event_at) + " ago" : "never" %>
              </p>
            <% end %>

            <% if @agent.can_receive_events? %>
              <p>
                <b>Last received event:</b>
                <%= @agent.last_receive_at ? time_ago_in_words(@agent.last_receive_at) + " ago" : "never" %>
              </p>
            <% end %>

            <% if @agent.can_create_events? %>
              <p>
                <b>Events created:</b>
                <%= link_to @agent.events.count, events_path(:agent => @agent.to_param) %>
              </p>
            <% end %>

            <% if @agent.can_receive_events? %>
              <p>
                <b>Event sources:</b>
                <% if @agent.sources.length %>
                  <%= @agent.sources.map { |source_agent| link_to(source_agent.name, agent_path(source_agent)) }.to_sentence.html_safe %>
                <% else %>
                  None
                <% end %>
              </p>
            <% end %>

            <% if @agent.can_create_events? %>
              <p>
                <b>Event receivers:</b>
                <% if @agent.receivers.length %>
                  <%= @agent.receivers.map { |receiver_agent| link_to(receiver_agent.name, agent_path(receiver_agent)) }.to_sentence.html_safe %>
                <% else %>
                  None
                <% end %>
              </p>
            <% end %>

            <p>
              <b>Working:</b>
              <%= working @agent %>
            </p>

            <p>
              <b>Options:</b>
              <pre><%= Utils.pretty_jsonify @agent.options || {} %></pre>
            </p>

            <p>
              <b>Memory:</b>
              <pre><%= Utils.pretty_jsonify @agent.memory || {} %></pre>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>